name: .NET Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore ./BigramParsing/BigramParsing.sln
      
    - name: Build
      run: dotnet build ./BigramParsing/BigramParsing.sln --no-restore --configuration Release
      
    - name: Run tests and collect results
      run: dotnet test ./BigramParsing/BigramParsing.sln --no-build --configuration Release 
